database: hsqldb

# Database Settings
spring:
  datasource:
    schema: classpath*:/${database}/schema.sql
    data: classpath*:/${database}/data.sql
    url: jdbc:h2:mem:testdb;MODE=mysql;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

  # H2 Settings
  h2:
    console:
      enabled: true
      path: /h2-console

  logging:
    level:
      org:
        springframework.web: debug
